### ISSUE TITLE
directory tree issue

### ISSUE THREAD

**Issue by gcojoc** [RI-imaging/DryMass#19]
'Case when a directory containing measurements without any subdirectory is given'

when applying ' dm_analyze_sphere.exe -r 'g:\00_test\'' a new directory is created, dir1_dm, at the main location: 
![181022_01](https://user-images.githubusercontent.com/34100125/47304008-c27e6f00-d625-11e8-913f-3fd807a99684.JPG)
Also a new directory is created at main_location\dir1\dir_dm:
![181022_02](https://user-images.githubusercontent.com/34100125/47304154-112c0900-d626-11e8-87d6-647c8f28ca63.JPG)

- [ ] I guess the correct operation should be:

![181022_03](https://user-images.githubusercontent.com/34100125/47304182-27d26000-d626-11e8-8250-2bb62f249b53.JPG)

**Comment by paulmueller** [comment]
Note that the "Sid4-285" data is redundantly stored in the zip file and is not necessary (can be deleted).
It must not be present when running DryMass in "--recursive" mode, otherwise DryMass will attempt to load these data as hologram tiff files, which does not work. If the folder "Sid4-285" is not present, DryMass will correctly identify the zipped series data.

**Comment by paulmueller** [comment]
see https://github.com/RI-imaging/DryMass/commit/dde5a5ee1a91a188ede8b252a931bac8f612dd87 for the falsely created _dm output folder
