### ISSUE TITLE
recursive analysis chrashes for dm_analysis_stretch

### ISSUE THREAD

**Issue by gcojoc** [RI-imaging/DryMass#25]
When performing recursive analysis on stretch mode, software stops at the instance it founds an error. 
Wouldn't be  better to report the error and pass to the next instance without stopping?

**Comment by paulmueller** [comment]
I disagree.
1. Known errors should be handled by DryMass and it is important that they get reported here so that everyone benefits from a fix.
2. Catching errors and displaying them after the analysis is done will add another level of complexity to the source code of DryMass. It is difficult to test such things and it generally looks ugly as well.

**Comment by gcojoc** [comment]
What do you disagree with? I still think that software stop. the recursive analysis when there is an error. 
Otherwise, I agree with both your points.

**Comment by paulmueller** [comment]
My main point is that there should not be any errors in the first place. If those errors are resolved (or treated gracefully during runtime), then the recursive analysis will also run through. Thus, there is nothing to do here.
